name: Test Scan Action

on:
  workflow_dispatch:
    inputs:
      image:
        description: "what image to scan?"
        required: false
        default: alpine:latest
      fail-build:
        description: "pass to fail-build on scan-action"
        required: false
        default: true
      severity-cutoff:
        description: "pass to severity-cutoff on scan-action"
        required: false
        default: ""

jobs:
  scan_action:
    runs-on: ubuntu-latest
    steps:
      - name: scan
        # uses: anchore/scan-action@49e50b215b647c5ec97abb66f69af73c46a4ca08 # v5.0.1
        uses: anchore/scan-action@v4.1.2
        with:
          image: ${{ inputs.image }}
          fail-build: ${{ inputs.fail-build }}
          severity-cutoff: ${{ inputs.severity-cutoff }}
      - name: assert_output
        run: |
          echo "${{ steps.scan.outputs.sarif }}$
          test -f ${{ steps.scan.outputs.sarif }}
      - name: upload the sarif report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }} 
